language: java
jdk: oraclejdk8
sudo: required
services:
- docker

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}
  - secure: UzgshZ4llk763J7rpU2RM8Gu7z3Ikg7hW5aMVdgnBFEBOiHa9gfOwHq7k472IA1EwnDaath7hrRyzl28ZP6X+n821QP5LjM90H3+GoHkUIHBCeFr0HA6+Qvljps8cch1NJKG0d8Xxisxgt89/U2UZM1FPQW/dT5IwT0PnOhJnuPUoZy8NOa+TmVBDe6gj6qjvcYKrwh8HIbzSaapPkcGf2+OZyDboq6qMVG92HnKVD79BXZf6/9asIxQtcMcKwWZkow22U0/PcvrtBGzy8I6LeuPO3hkdM4X6CAFkYOYHG4/83CrQOcd5l2+ENbz8omo2ijeEGhx37bjX09R9TlzidFLE40wlixv+4pEYdPyy0uQH1pKhCrKyxrd7BlhwAHRcqlFVQQoLv5YBKNgL6KLMB1w9EIRE9mnIHEIXaZok0ob28eWrkO3axEov4BgA74J2qjMXVKFVh5he8mHmW4w0CqdriorsGy1Q+Bv7qxj6t1J+2M9dZyds3B1W+g32Di6c3tgGmIrvBTCjqEs70EjFQv51xnRqTcwD0MdM7mqmHv9WJdVwps8QoAEuj6ZLxk2JiiBLJMRFXEc43CAvKOzIH2HYftEBeD8pbGCaCpWrhuC1DD8n1ApduFD5eBFSeiNIJK9A0iSUYeAaitKaO0XdQm1a2U7ufIVwIR6WYedtoM=
  - secure: TNyNQdYOcE9pL1Ju61EXhVK16bo/yo9WN6Ejtkg/RkhepJatICo+xyYBW4EEjsBUYi7Vhi6kcGmjekGqxQlhKqEnSPqoLmAbGC9g21JYKwZUJN4umPwkGcvC/7Bv3Gl1FmWFCkmHEMWaKblV+XxoWWaPOWpu9aKQ8M1tvVFGMindWHCS5WwcH4iLo6OhPW+qEXAc24x76YI4vr0vCgBw65AsuwEi82L9R7gRk3LCaCV5D1MqHcGJQoz/xmCwl5RYZzgYwbqEj0RSsKG1qCFznPeTy4ZFDWAjelMAloAKTcCw/g6zt98+4teIOMVO+tOjlrz+7pYkduuRnxASxPuVE0xEQL3MDXFYh2q5PzXYfyxjmOlnFETH6JGz//tP3MIflK21BeUVwViRaq9ETFYpZbgkxbyuBihkhrwIs4F3PP0ujOwXF0cNKt6/V+qEUNenJfvTSv3kEamFqlWA3lT6tU5qlI3eeNbncd7tKPXp/yiH9jsd9JpUvuSatHRu6hAoOwmY032RNKVbF8mz7BY9gkKi1mrcNsiPt0VpcNy+1FTJ7GSVU2qmDggsSr7mRd7MMw84ii7nK0emGo45oFDtrPxsbzBJG4R54ab1yhj1GPHzwERBKIEn3dm+YJSVN/MEvyFcq+Jl7qE8zRKazJ6AM0mCDNnwOGRYOdUQpd0ko6A=

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- export IMAGE_NAME=fernandonogueira/promeureka
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
