eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
spring:
  application:
    name: PROMETHEUS-EUREKA

prometheus:
  jsonFolder: ${JSON_FILE_PATH:test}

