spring:
  application:
    name: PROMETHEUS-EUREKA

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

prom-eureka:
  json-file:
    path: ${JSON_FILE_PATH:/tmp}